### ISSUE TITLE
4/27 Hotfix--Needs Op Code update

### ISSUE THREAD

**Issue by princeabooboo** [Soreepeong/XivMitmLatencyMitigator#10]
Hello!  Just wanted to let you know that the hotfix today makes this not work at the present time, but I am sure slight tweaks will have it up and running again.  Thank you!

**Comment by princeabooboo** [comment]
I believe these are the necessary changes:

{
    "ActorCast": "0x02ad",
    "ActorControl": "0x02db",
    "ActorControlSelf": "0x023e",
    "AddStatusEffect": "0x0334",
    "RequestUseAction": "0x00d0",
    "RequestUseAction2": "0x0094",
    "SkillResultResponse01": "0x03e7",
    "SkillResultResponse08": "0x020a",
    "SkillResultResponse16": "0x01f9",
    "SkillResultResponse24": "0x01eb",
    "SkillResultResponse32": "0x013e"
}

**Comment by Soreepeong** [comment]
It's now done with 88a08e5.
