### ISSUE TITLE
Latency Correction

### ISSUE THREAD

**Issue by YOxidized** [Soreepeong/XivMitmLatencyMitigator#11]
Hello!

First, allow me to thank you for this amazing tool, allowing PS4 players to experience the same benefits as those who use XIVAlex.  Right now, the two seem to be nearly identical in performance, but there is something I have noticed in my own experiences with the LatencyMitigator; whenever I am moving and/or in instances with multiple people (8-man raids included), I will occasionally clip and experience inconsistent performance.  This is a result of the c2m latency being much lower in these cases (I have seen it be 10-30ms in a crowded instance, but 80+ ms in a solo instance), which widens the gap between latency and delay.

Supposedly, XIVAlex has a latnency correction feature, and if such a feature could be added to the LatencyMitigator to account for this, it would greatly improve the consistency of this tool.  Thank you!

**Comment by Soreepeong** [comment]
I forgot to check this issue, sorry about that. Currently, this will flatly subtract the ping to either direction (to game server and to your client), so should directly reflect the server processing delay. It definitely is possible to average out the fluctations, so I'll consider doing that.

**Comment by Soreepeong** [comment]
It's now implemented.

**Comment by YOxidized** [comment]
Thank you, it works really well
