### ISSUE TITLE
Trouble making this work

### ISSUE THREAD

**Issue by Alviau** [Soreepeong/XivMitmLatencyMitigator#18]
Hello! I'm prefacing this by saying I really don't know where I want to get with this because I don't expect you to troubleshoot this for me, it's a lot of things and you probably have better things to do than deal with my dumb ass, as this could prove time-consuming and frustrating. But I want to provide my experience with setting this up.

I've been desperately trying to make this work all day with a laptop running Windows 10 Home and my PS4 but I keep running into different errors. I'm completely unfamiliar with Linux and virtual machines so from the get go this is a whole new realm for me. Even with the instructions provided I'm struggling a lot, I'm really not a techy type person.

I've tried Hyper-V on Windows 10 Home with a workaround I found on another website since it typically won't work on Home and requires upgrading to Pro, which I can't afford. Said workaround was successful and enabled Hyper-V but when I finally get to step 4-xi to power up the virtual machine I get this: https://puu.sh/HQV9a/21e05bdde0.png which I tried to look up on Google and I just can't make heads or tails of it. Too many terms and things thrown around I don't understand at all.

I tried VMware and VirtualBox too, and I run into several other errors along the way. It's too many things to list and I don't remember most of them at this point, so I'll just speak of my latest attempt. With VirtualBox and an Arch Linux ISO I got to this point: https://puu.sh/HQUJN/a9fabe20f8.png

No errors or anything that I understand to be an error, but I do realize it's still perfectly possible the virtual machine or its connection to the network aren't set up correctly. So after getting there, when I go to my PS4 to set up a new internet connection, I put in what I think (I'm really not sure) are the correct IP Address, Subnet Mask and Primary & Secondary DNS, and for Default Gateway I introduce 10.0.2.15 and then the PS4 just won't get connected to the Internet at all. So I'm really stuck because no matter what I do or where I get to, something makes me hit a brick wall and I feel too dumb at this point to make this work and I'm just defeated, I give up.

But I do want to thank you for making this and XivAlexander (a lot of my friends use it) and providing it for free, and thank you for your time reading my frustrations. And I also want to say my apologies if this was a waste of time to read.

**Comment by ayyaruq** [comment]
The Hyper-V instructions include setting up an external switch. VirtualBox doesn't work this way, but iirc the Bridge network mode should be pretty close (go to VM settings, network adapters page, select the NIC, set mode to bridged). Once the VM is bridged into your main network, it will route via your normal Windows network but still have an IP the PS4 can resolve. Then you can grab the IP from the `ifconfig` output inside the VM and pass it to the PS4 as normal. That should sort out what you need. On the PS4, you should only need to set the gateway IP and leave everything else on defaults other than maybe MTU (depends if you use Mudfish or similar). I'd try if the "easy config" mode works better tho.

Not sure what the deal is with Hyper-V error tho.

**Comment by Alviau** [comment]
Hey! Thank you so much for your response. I managed to make it work with VirtualBox. I was missing the setting to bridged mode part, silly me. I've been testing ingame and it works very nicely so far. One last question, which is probably a really dumb one, but do I have to set the virtual machine up with the commands every time I log in or just powering it up would suffice? In any case, thanks so much.

**Comment by Soreepeong** [comment]
The problem about `initfs unpacking error` might be something about this: https://askubuntu.com/questions/1180415/initramfs-unpacking-failed-write-error 

You can also install a linux distro of your preference, install `iptables-persistent` if it requires you to, do `iptables-save` after step 6, and possibly make step 7 into an autostarting systemd unit.

**Comment by Alviau** [comment]
I think for the time being everything is working. I've tried turning everything off and back on and still works, I'm pretty happy with it. If anything comes up again I'll make sure to fiddle with things thoroughly before having to ask again. Thank you for all the help, really appreciate it!

**Comment by ayyaruq** [comment]
If the IP is changing between VM boots, you can grab the MAC address of the NIC in vbox settings and in your router, assign a static IP for the MAC. It'll be dynamically allocated via DHCP but it'll be consistent so your PS4 won't need updating.

**Comment by RaphaelDDL** [comment]
I bumped into same issue as OP when setting up now. Picking install archlinux would always end on `initfs unpacking error`. 

What worked for me was the last comment on askubuntu.com link posted by Soreepeong, which was to make the VM RAM be 1024MB. Both 256mb suggested by Readme and 512 would end up dying on initfs error.
