### ISSUE TITLE
Game freezing/disconnecting randomly

### ISSUE THREAD

**Issue by Alviau** [Soreepeong/XivMitmLatencyMitigator#19]
Hello! Thanks for the help the other day and I'm sorry to bother again.

I seem to run into some sort of stability or connection issue where suddenly the game will stop processing my actions and everything either completely freezes or, more often, I will see people/enemies moving around a bit and eventually completely stop and myself autoattacking. When this happens and I execute actions I'll see the animation but no damage, the next combo won't light up, etc. I end up having to force close my client and having to set up the connection again or run without the mitigator. I don't run into connection issues without it.

Here's a log of what happens, where you can notice a sharp increase in "delay" at the time I run into the issue.
https://puu.sh/HS8Vv/996279c115.png

Sometimes this happens as soon as 5-10 minutes into playing, sometimes it takes a bit longer, and the other day I ran several roulettes in a row with no issues. I've been mostly playing MCH and DRG (log above is MCH).

I know this is most likely an issue on my end as I'm still not fully sure if my VM and PS4 connection are set up 100% correctly. I can provide any other data you might need.

_Edit:_ I will also add that when I set up the connection for the mitigator, the download speed shown on PS4 when testing the connection tanks pretty low compared to my regular connection, is that normal?

**Comment by Soreepeong** [comment]
1. I'll test it out for extended time, but note that it can happen when your ISP does not like long living connections when it has additional gateway (the VM). 
2. Yes, that is expected, but the latency itself shouldn't differ much.

**Comment by Soreepeong** [comment]
It did work fine for me for like 4 hours. VirtualBox as I remember isn't very stable - can't tell for now but - so maybe try out VMWare Player? If its default bridge setting does it wrong, try out this: https://www.serverwatch.com/guides/how-to-fix-a-vmware-player-bridged-network/

**Comment by Alviau** [comment]
Hello, thank you so much for taking the time to check. I've made the switch to VMWare, been trying it all morning. I've been doing some stuff and it seems to last longer, but it does still DC sometimes. In about 4-5 hours I had 3 DCs, which isn't that bad but still not reliable if it happened mid-raid or something. Probably nothing you can do there if it's working perfectly fine on your end, seems to be entirely on mine, be it my ISP being dumb or something on my network... I've been thinking maybe it's my laptop, it's quite low-end.

This might be a stupid question, and hopefully my last as I don't want to take more of your time, would my DNS settings impact stability significantly? If so, which do you recommend? Not sure if mine are solid.

Once again thank you so much.

**Comment by Alviau** [comment]
I seem to have found what the problem was and fixed it. I have had no more disconnects since. I was checking my adapter options and noticed a lot of these items, including bridge protocols, were disabled for whatever the heck reason.

https://puu.sh/HT48a/c341ce4bce.png

I enabled them on the relevant adapters. I guess the connection was throttled without those things. So if anyone is having stability issues while trying to run this from a Windows machine, go to Network & Internet Settings, Change adapter options and check if on properties anything's amiss.

Thanks for all the assistance and for your work on this tool, I was in TEA just now and it makes a world of a difference with how consistent my rotation is now without stupid GCD clipping, I have everything landing when and where I want.
