### ISSUE TITLE
Client stops accepting skill inputs

### ISSUE THREAD

**Issue by SimonPilkington** [Soreepeong/XivMitmLatencyMitigator#2]
I am playing from the EU on the NA datacentre and I discovered a problem where while using this my client will completely stop reacting to all skill inputs after a brief time. This follows this log message: https://github.com/Soreepeong/XivMitmLatencyMitigator/blob/0d853f3a396fb77d44414f9cfe0a2efee0685cae/mitigate.py#L479

I was seemingly able to get around the problem by raising `EXTRA_DELAY` (to `0.125`) but it is still quite worrying as it could suddenly turn me into a waste of space during an instance and I'm not sure how reliable my workaround is. The only way to make the client accept skill input again is to log out and back in. Do you have any idea what's happening?

**Comment by Rawrington** [comment]
Pretty sure the reason for this is the message after this will show a modified animation lock of a negative number (i.e. -500ms~ for me), I added a check to see if hte wait time is below 0 and corrected it to EXTRA_DELAY if that happens as a temporary fix but i dont know if this is the way to go

**Comment by Soreepeong** [comment]
Rawrington's right - Yeah, the animation lock would become not right when a negative value is given. Comparing source code with the Windows version of the addon, I missed adding non-negative guarantee for this one. I just fixed it and am testing it right now.

Also, it now saves log to a file in /tmp too. If it's still causing problems, please attach the log file.

**Comment by Soreepeong** [comment]
The problem was actually about me writing opcode for action rejection wrong. It's now fixed. curl'ing might not reflect the most recent changes right way, in which case, you might have to use `git clone https://github.com/Soreepeong/XivMitmLatencyMitigator.git` instead.

**Comment by SimonPilkington** [comment]
I have played a five hour session just now and did not encounter the issue again, thank you for fixing it, and also for making this in the first place. The difference is night and day, and classes like MCH are actually unplayable without.
