### ISSUE TITLE
Docker

### ISSUE THREAD

**Issue by Arcayr** [Soreepeong/XivMitmLatencyMitigator#20]
Pretty sure just by putting that in the issue title I've become that which I hate, but ...

Have you tried containerising this in any way, so that people on Linux/Mac/whatever can just run a container on the PC they're playing on?

I messed around with it a little bit but the codebase is pretty rigid about its forwarding rules at present.

Cheers,

Arc

**Comment by Soreepeong** [comment]
I would guess you will need external iptables configurations to pass over connections into docker, no? Unless you can make a docker container fiddle with outside iptables, or there exists an easy way to have an interfaced bridged into a container, I don't think dockerizing this would make stuff easier.

**Comment by Arcayr** [comment]
I think there might be. I'll play around with it a bit more and get back to you. The fork model that is now being used causes the container to exhaust its nproc ulimits, so I'm seeing what can be reasonably done about that.

**Comment by magoolachub** [comment]
I don't have a solution for this per se but for anyone who is playing FFXIV on mac/linux and is looking for a way to run alexander, consider purchasing a raspberry pi and using it to run this script then routing your game traffic to the pi. It's relatively cheap and works well :)

Thank you for your work Soreepeong.
