### ISSUE TITLE
No longer working after patch

### ISSUE THREAD

**Issue by mariliaek** [Soreepeong/XivMitmLatencyMitigator#21]
Hey there, found this tool within the past week and it has been a godsend! I've been running it on a laptop I don't really use, connected to ethernet since the VM wasn't working on wifi. My PS4 is then connected to the internet via the VM.
The tool worked perfectly until today, and I was wondering if that would be due to the 5.58 patch. When I type in the curl command it appears to download, but once I'm in the game it doesn't print any more logs and my latency is as usual. Additionally, every time I press Control-C to exit and try to restart it immediately disconnects me from the game.
Just wanted to make sure that the tool will be working again soon! Can't believe I've lived this whole time without it, thank you very much for the work

**Comment by YOxidized** [comment]
This is because the opcodes have changed, and the program is not pulling in the correct ones.

**Comment by mariliaek** [comment]
I suspected as much, I did check the XivA page before posting and saw a recent update. I'll be away from home for a few days anyway so I'm not in any rush! ty for the reply

**Comment by lucasp-andrade** [comment]
@mariliaek 
You closed the issue, but you can easily fix this problem yourself by deleting the "definitions.json" file and executing the script again. It will then download a new definitions.json file with updated opcodes from XIVAlexander repository.

Basically, the script does not check if the the XIVAlexander repository was updated, only checks if the "definitions.json" file exists in your folder. So if there was an definitions.json from a previous execution in your folder (before the game update), it will keep loading the outdated opcodes from it until you delete your old json or update the opcodes yourself. I am not sure if this behavior was intended or not.
