### ISSUE TITLE
Random "Action" (possibly shuffled auto attacks) takes place in E9S (Eden's Promise: Umbra)

### ISSUE THREAD

**Issue by Rawrington** [Soreepeong/XivMitmLatencyMitigator#3]
I've been speedrunning e9s with this on and off and for some reason it keeps spitting out this:
`[5] 2021-02-14 19:54:13.667681  ┎ Not user-originated, and isn't an auto-attack (00f5)
[5] 2021-02-14 19:54:13.668266 S2C_ActionEffect: actionId=00f5 sourceSequence=0000 wait=100ms`
the id has been different between sessions I remember it being 00ba once for certain (yesterday)

I feel that perhaps the auto attack id is shuffled in this instance perhaps?

I'm playing Dancer and it happens in this instance, can't confirm for any other savages since my group has been focusing on this one.

I assume XivAlexander would have the same issue, attached is the full log from today.
[xmlm.20210214155118.5.log](https://github.com/Soreepeong/XivMitmLatencyMitigator/files/5978552/xmlm.20210214155118.5.log)

**Comment by Soreepeong** [comment]
This looks horrible to debug, but I'll see what I can do. Maybe there is no need to differentiate autoattacks by Action ID, and we can just treat all ActionEffect with sourceSequence 0 to be having 100ms animation lock.

**Comment by Soreepeong** [comment]
I've changed the processing of auto attacks; details can be read at https://github.com/Soreepeong/XivAlexander/issues/12 .
