### ISSUE TITLE
No longer reducing latency on PS4 as of latest patch

### ISSUE THREAD

**Issue by tormink** [Soreepeong/XivMitmLatencyMitigator#32]
I've configured the software to run on my linux machine and have setup a static IP on my ps4, and it's worked for months. But as of the latest version, it hasn't worked anymore. I get the same amount of latency on action presses as I normally do. However, it does seem the program is capturing my inputs since it is logging stuff, so in theory it's still correctly configured. 

I've tried several times making it download the opcodes again since they were updated, nothing changed, really. 
Here's a screenshots of some of the logs as I try hitting dummies in-game:
![image](https://user-images.githubusercontent.com/12940237/147030558-0140d0b0-c993-4481-8542-3f651127fbf5.png)

Also, one bizarre behavior change I've noticed is that: normally after setting up the static IP on my PS4 and setting the gateway to point to my laptop, it will not have a working internet connection until I run the script. However, after today, it does seem to work normally with the static IP pointing to my machine regardless of me running the script. Now I'm not a networking person and I do not know if this has anything to do with anything, but it is something that changed so I'm stating it here.

I apologize if I failed to cite any steps or issues I've had, but if it's something I'm doing wrong, please tell me so I can fix it. 
Could it be because I'm not using a VM with no memory and just my own linux machine? I've tried running the iptables commands following the step by step guide again but it changes nothing, either.

**Comment by Soreepeong** [comment]
Try downloading the script and run again. I've fixed the issue where the modification to packets wasn't actually being applied.

**Comment by tormink** [comment]
It seems to be working again for me after trying it today, seems the problem has been solved. Thanks!
