### ISSUE TITLE
Does this make an assumption that you're running a VM closer to the data center? 

### ISSUE THREAD

**Issue by seivan** [Soreepeong/XivMitmLatencyMitigator#36]
The reason I asks, is could I just boot up a docker VM on my machine directly and use that instead? 
Or why not just run the python script directly on my machine? 
I'm sure I've missed something, so asking for clarification. 

Edit: So the script intercepts the traffic and responds to the client the necessary ack to allow abilities to be used, circumventing waiting for the servers ack, did I get it right?

**Comment by Soreepeong** [comment]
No, it will change the server response to have animation lock duration reduced by the duration of round trip from the VM to the servers. This script should be running as close as possible to your gaming rig.

**Comment by seivan** [comment]
So have you ever tried using it with a Docker container?
I might try that, but any input or pointers if you have any experience doing that?

**Comment by Soreepeong** [comment]
If you can give the docker container an IP address visible to your router and the gaming machine, then it probably will work, but then again if iptables is not available for docker, then it won't be. I've only tested this on VM.

**Comment by seivan** [comment]
Yeah so the container would run locally on my machine(host) and the host would redirect traffic to it.
I'd just need to know the port in advance, and the script seems to randomize the port it listens to(?) - any chance that could be an argument to the script?

**Comment by Soreepeong** [comment]
Just replace line 1103 to the port you'd like to use for now.

**Comment by seivan** [comment]
> Just replace line 1103 to the port you'd like to use for now.

Will do. 
Is there a way to test that the communication between host and container works fine using the script alone without adding routes on the host machine? 
Assume I've run `iptables -t nat -A POSTROUTING -s <local_ip> -o <device_name> -j MASQUERADE` on the container.
Can I use netcat or telnet somehow to check that I can access `<local_ip>:<port>` with any data?
