### ISSUE TITLE
Not working with the new patch (2/16/2021)

### ISSUE THREAD

**Issue by princeabooboo** [Soreepeong/XivMitmLatencyMitigator#4]
This utility is not working with the new patch, but I assume this is for reasons similar to ACT being down after a new patch releases, so I am not too surprised, just an FYI if you were unaware of this.  Thank you!

**Comment by Soreepeong** [comment]
I just updated it. See if it works now, after re-downloading. If nothing changes, you might have to do `git clone https://github.com/Soreepeong/XivMitmLatencyMitigator.git` instead.

**Comment by princeabooboo** [comment]
Hmmmm, re-downloading did not seem to fix the issue, and typing `git clone https://github.com/Soreepeong/XivMitmLatencyMitigator.git` into the VM did not appear t do anything, either.  I apologize, I am not the most tech savvy, and this may just be a product of user error and/or failing to follow instructions correcty.

**Comment by Soreepeong** [comment]
Actually try it again right now. I mixed up KR and INTL opcodes.

**Comment by princeabooboo** [comment]
It works!  Great job on the coding btw, this is a great tool for anyone who has to deal with sub-optimal ping.  Thank you again!

**Comment by Soreepeong** [comment]
Thanks for confirming it works now!
