### ISSUE TITLE
Can't update opcodes after recent XivAlexander commit

### ISSUE THREAD

**Issue by Mayushii-chan** [Soreepeong/XivMitmLatencyMitigator#41]
Hello,

When trying to run the script I get the following errors in the screenshot below: 

![Screenshot 2022-03-17 at 07 24 34](https://user-images.githubusercontent.com/101785515/158749908-02aeac54-e7ee-4fe9-8cd2-87017e64233e.png)

I believe it is caused by the addition of this new file in a recent commit to XivAlexander:
https://github.com/Soreepeong/XivAlexander/blob/6e5d42402f972478fc6893ea6280eedc3d355d49/StaticData/OpcodeDefinition/notes.txt

To test I forked XivAlexander and XivMitmLatencyMitigator, deleted notes.txt and changed "OPCODE_DEFINITION_LIST_URL" in "mitigate.py" to point to the fork and it was now able to update opcodes like normal.

(I'm extremely new to GitHub, so I'm sorry if I did anything wrong.)

P.S. Thank you for creating this tool. I can finally enjoy playing the game after years of being unable to double weave.

**Comment by Soreepeong** [comment]
It's now fixed; it'll work if you download/run the script again., and if it doesn't work right away, try again after like 5 mins. Sorry about that!
