### ISSUE TITLE
Is there a way to use XivMitmLatency Mitigator wireless?

### ISSUE THREAD

**Issue by DiegoSalazar231** [Soreepeong/XivMitmLatencyMitigator#44]
Hi. I already installed xivmitm on my ps5 and works awesome, but the last week I had to move all my room through other one where I have only 1 ethernet cable so I connected to the console. Now the problem is that I don´t have other one for the pc and I can´t find a way to config the vm to work wireless. That´s why I´m making this post, I´ll appreciate if someone can help me :3

**Comment by Soreepeong** [comment]
You can try your VM take over complete control over your wireless card, and then route your PC's entire traffic through your VM. Not sure if it's possible to bridge a wireless network into a VM.

**Comment by Mayushii-chan** [comment]
Have you tried it the other way around? Cable to PC and wireless on PS5.

**Comment by DiegoSalazar231** [comment]
> You can try your VM take over complete control over your wireless card, and then route your PC's entire traffic through your VM. Not sure if it's possible to bridge a wireless network into a VM.

I´m not sure how to do that, but hopefully it works the way that said @Mayushii-chan uwu Thanks to both
