### ISSUE TITLE
Step 7 issue: ffxiv.exe

### ISSUE THREAD

**Issue by DiegoSalazar231** [Soreepeong/XivMitmLatencyMitigator#48]
Any idea how to solve this? I installed xivalexander months ago, but with the new steps we have to do to make it work again, I'm a bit lost. I tried to pick another ip from HFS, but it keeps saying the "connection timed out", or the other one if i choose the same ip on HFS than the local one, but I don't know if that's good. I'd really appreciate if someone help me, xivalexander is so damn good.

![20220610_165315](https://user-images.githubusercontent.com/98240637/173156550-e7af9267-547d-4ca9-8048-eba5c990ae25.jpg)

![20220610_165836](https://user-images.githubusercontent.com/98240637/173156560-44dbc56d-f71a-4f4c-a4cb-3f745afd787c.jpg)

**Comment by Mayushii-chan** [comment]
I don't know if it could interfere, but have you tried to temporarily disable your firewall, etc?

Alternatively you could try using http.server / SimpleHTTPServer: https://developer.mozilla.org/en-US/docs/Learn/Common_questions/set_up_a_local_testing_server#running_a_simple_local_http_server

**Comment by DiegoSalazar231** [comment]
I desactived my firewall, but I recieve the same message as the photos. I did the steps of that url, but I'm not sure how apply that on a linux command. I mean, what do I have to replace? I can't find any ip there. I really don't have too much experience here, sorry if I don't know the basics. Thanks though

**Comment by brunoyo** [comment]
I am having problems at step 7 as well. After I run HFS with the exe file there, when I try to get the file through the "default" ip I get the error "No route to host", while all the other options return a connection timeout... Having never used hyper-v and archiso before, I am probably missing something at the config, but no idea of what it could be :/

**Comment by Mayushii-chan** [comment]
@DiegoSalazar231 The IP you want to use is the local IP of the computer you are running the VM on.

**Comment by DiegoSalazar231** [comment]
@Mayushii-chan I did it. The problem was that I didn't knew I had to download the ffxiv.exe from the official page. But now, when I try to install gcc through the command "pacman -Sy gcc" it says "not enough free space".  And I don't completely understand what Soreepeong says in his guide there "if it fails due to not enough free space, then you will have to install the operating system instead of running on an installation media" :c

**Comment by Arkzera** [comment]
@DiegoSalazar231 You have to install the iso instead of just running it without any install required, attaching an hard drive and stuff. I honestly recomend you to use Lubuntu for it.

**Comment by Flaviorsb** [comment]
> @DiegoSalazar231 Você tem que instalar o iso em vez de apenas executá-lo sem qualquer instalação necessária, anexando um disco rígido e outras coisas. Eu honestamente recomendo que você use Lubuntu para isso.

X86 or 64?

**Comment by Arkzera** [comment]
> > @DiegoSalazar231 Você tem que instalar o iso em vez de apenas executá-lo sem qualquer instalação necessária, anexando um disco rígido e outras coisas. Eu honestamente recomendo que você use Lubuntu para isso.
> 
> X86 or 64?

https://lubuntu.me/downloads/ Im running it on the LTS (Jammy Jellyfish) 64-bit

**Comment by DiegoSalazar231** [comment]
Is okay if I use Ubuntu? I installed it a couple of hours before and I maked a little progress (which I'm happy about it). I also run "sudo apt-get install python 3", but appears still a permission error. Did it happened to you?

Btw, I also downloaded ffxiv.exe there

![16549814542403169675304674707060](https://user-images.githubusercontent.com/98240637/173204843-cc38a9bc-e302-4c45-af18-e82e9e29816f.jpg)

**Comment by Arkzera** [comment]
> Is okay if I use Ubuntu? I installed it a couple of hours before and I maked a little progress (which I'm happy about it). I also run "sudo apt-get install python 3", but appears still a permission error. Did it happened to you?
> 
> Btw, I also downloaded ffxiv.exe there
> 
> ![16549814542403169675304674707060](https://user-images.githubusercontent.com/98240637/173204843-cc38a9bc-e302-4c45-af18-e82e9e29816f.jpg)

do `sudo apt install g++ gcc-multilib g++-multilib` and try again

**Comment by DiegoSalazar231** [comment]
> 

Did you drag the file ffxiv.exe from the game folder to HFS? I solved it doing that. Besides, the line "iptable" must be with the vm ip. I hope that works for you as well.

**Comment by DiegoSalazar231** [comment]
I just did it before, but nothing changes. I'm not sure if this might interfere, I download mitigate.py and xivmitm folder inside Ubuntu. Just saying if that's the issue

![16549834246345521915309611097319](https://user-images.githubusercontent.com/98240637/173205720-4c639ee8-f012-447c-93aa-7e823319f280.jpg)

**Comment by DiegoSalazar231** [comment]
@brunoyo Did you drag ffxiv.exe from the official game folder to HFS? I didn't before, but I solved that same message doing that, I had to download the free trial since I play on console. And the "iptables" line must be with the vm ip, just in case. I hope that works for you as well

**Comment by Arkzera** [comment]
Try as sroot user, do sudo -i

**Comment by DiegoSalazar231** [comment]
I guess that works, now says this:

![16549841301681985151208107327682](https://user-images.githubusercontent.com/98240637/173206006-99941ddb-dc5a-4e17-aa32-09838d6d41fb.jpg)

I really appreciate your help.

**Comment by Arkzera** [comment]
> I guess that works, now says this:
> 
> ![16549841301681985151208107327682](https://user-images.githubusercontent.com/98240637/173206006-99941ddb-dc5a-4e17-aa32-09838d6d41fb.jpg)
> 
> I really appreciate your help.

Open HFS, throw ffxiv.exe in there and do `curl -O ffxiv.exe http://<HFS-IP>/ffxiv.exe`. U might need to change the ip on HFS until one of them works, u can do it on Menu > IP address

**Comment by Flaviorsb** [comment]
if you are having problems with HFS, use onedrive or dropbox, open the site in your browser and copy it to the /home folder.

work here

**Comment by Flaviorsb** [comment]
> > > @DiegoSalazar231 Você tem que instalar o iso em vez de apenas executá-lo sem qualquer instalação necessária, anexando um disco rígido e outras coisas. Eu honestamente recomendo que você use Lubuntu para isso.
> > 
> > 
> > X86 or 64?
> 
> https://lubuntu.me/downloads/ Im running it on the LTS (Jammy Jellyfish) 64-bit
> 
> After installing you'll need to install curl and enable python scripts to run For curl i used this guide: https://www.cyberciti.biz/faq/how-to-install-curl-command-on-a-ubuntu-linux/ For python just run the code `sudo apt-get install python3`

Thanks lunbuntu work here.

**Comment by Rappy28** [comment]
> @Mayushii-chan I did it. The problem was that I didn't knew I had to download the ffxiv.exe from the official page. But now, when I try to install gcc through the command "pacman -Sy gcc" it says "not enough free space". And I don't completely understand what Soreepeong says in his guide there "if it fails due to not enough free space, then you will have to install the operating system instead of running on an installation media" :c

I see from your later comments that you ended up installing Ubuntu to get around this issue. But for the benefit of whoever else might be reading this, I want to mention you can still install gcc on the Arch ISO installation media without having to install the whole OS.

Just hit Tab when you are booting up your VM. It's going to bring up a line of options on the bottom. Add `cow_spacesize=1G` at the end of the line then continue the VM launch as usual. This gave me enough disk space to install gcc and its 32-bit lib.

As far as I know there is no drawback using this method. I was able to use the Latency Mitigator just fine just now.

**Comment by DiegoSalazar231** [comment]
@Arkzera Finally I did it. I was able to make it work running again "curl -o ffxiv.exe http://<HFS-IP>/ffxiv.exe" after "sudo -i". Thanks a lot for your help and time :D 

@Rappy28 Ohh good to know, I've already installed, but thanks though. Surely it will help other people that might get troubles at that step.

**Comment by brunoyo** [comment]
I ended up restoring windows and got some progress, but now I am at the point of not enough free space.

@Rappy28 I tried using the solution you provided but I don´t know if I can use that in hyper-v. I searched at youtube an example and in the video they were using Oracle VM, pressing tab at the hyper-v does nothing at the boot.
