### ISSUE TITLE
Route Ordering

### ISSUE THREAD

**Issue by ayyaruq** [Soreepeong/XivMitmLatencyMitigator#5]
When using with a VPN like Mudfish, what is the expected route order? Mudfish creates a TUN interface but I'm unclear on if iptables is supposed to be natting the tunnel or the underlying interface to the default gateway, or if additional rules are required.

There's no encryption as far as I'm aware, it's just a standard layer 3 tunnel. It'd be good to get some clarification on expected routing between a console and the servers when both the mitigator and a "VPN" are running, especially with the intended source and device for masquerading.

To clarify a bit, as far as I can tell the NAT rules for prerouting are fine as is, but postrouting would require the full local subnet as the source and then an entry for both the eth0 (or whatever) interface as well as the vpn interface, so something like this:

```
iptables -t nat -I PREROUTING -d 124.150.157.0/24 -p tcp -j REDIRECT --to 9999"
iptables -t nat -A POSTROUTING -s 10.0.0.192/26 -o eth0 -j MASQUERADE
iptables -t nat -A POSTROUTING -s 10.0.0.192/26 -o tun0 -j MASQUERADE
```

I used a random port here as an example, and I'll also note that SE DCs don't use /24 networks, but yolo.

**Comment by Soreepeong** [comment]
I'm not sure about what you're asking, by "expected route order." All I was concerned was taking control of all connection of SE DC when the box is acting as a router: if I understood the question right, it would be:

```
game device (-> Switch) -> linux iptables -> redirected to XivMitmLatencyMitigator -> open socket connection to SE DC using the operating system's default routing table (will be routed via mudfish here) -> ...
```

XivMitmLatencyMitigator will use routing rules from `ip route`, which mudfish should have added an item there.

Yeah, I don't think they would use the whole /24 subnet, but wasn't sure how to figure it out else than trying to connect to all available servers, and make sure that there aren't any other servers that aren't listed on the page https://is.xivup.com/adv . Well, if it works then it works! Would definitely update it if the IPs listed on that page are the definitive list of game server IPs.

**Comment by ayyaruq** [comment]
Essentially I wanted to confirm where the app expects to be between iptables rules and the routing table. I think it's clear now tho, thanks!

Re subnets, the primary allocations are /21 but the FFXIV game servers specifically are /27 blocks iirc.

**Comment by Uragawa** [comment]
To anyone looking at this in the future, I'd like to share that I (a bumpkin when it comes to routing tables) was able to get xivmitmlm and Mudfish working together without extra configuration steps by running Mudfish from within the VM where xivmitmlm runs. That way the game device (the Linux host computer in my case) only has to worry about routing to xivmitmlm.
