### ISSUE TITLE
Oodle test fail

### ISSUE THREAD

**Issue by Kashozs** [Soreepeong/XivMitmLatencyMitigator#50]
Hi, i just downloaded ubuntu but when i run the curl command i get this
![image](https://user-images.githubusercontent.com/107314363/173409801-820ab1b5-d016-4113-b7d5-fa38afaa83b1.jpg)
 Also since i have installed ubuntu HFS.exe and ffxiv.exe dosent work ( as far as i know exe files dosent work on linux machine) anyone has an idea ?, Thanks in advance

**Comment by DiegoSalazar231** [comment]
I had the same problem just yesterday. I fixed it running again "iptables ..." line and checking again if the ip from my default gateway console was placed correctly. Somehow, it changed which I´m not sure why, but doing those things it´s running ok now

**Comment by Kashozs** [comment]
> I had the same problem just yesterday. I fixed it running again "iptables ..." line and checking again if the ip from my default gateway console was placed correctly. Somehow, it changed which I´m not sure why, but doing those things it´s running ok now

Didnt work for me, btw, does HFS work for you while you are using ubuntu ?

**Comment by Kashozs** [comment]
I tried running archlinux through VM but it says not enough disk space, then i tried installing the VM but it says some errors about oodle_helper, i also tried installing ubuntu OS 22.04 but it still the same problem as the picture apove, please if anyone has an idea or something i'd appriciate your help. ^^

**Comment by steponmepls** [comment]
> as far as i know exe files dosent work on linux machine
I think you are supposed to install and launch HFS on your windows client, drag and drop the ffxiv.exe inside and then use the curl command inside the linux virtual environment to download the file from your local ip

**Comment by Kashozs** [comment]
> > as far as i know exe files dosent work on linux machine  
> 
> 
> 
> I think you are supposed to install and launch HFS on your windows client, drag and drop the ffxiv.exe inside and then use the curl command inside the linux virtual environment to download the file from your local ip

Thanks it worked ^^. I spent 11 days trying to find the problem XD.
I really appreciate your help <3
