### ISSUE TITLE
Curl not working 

### ISSUE THREAD

**Issue by LegendOfMatt** [Soreepeong/XivMitmLatencyMitigator#56]
Everytime I try running curl I get this error. Have tried looking and researching the issue and have found no solutions so far.
![image](https://user-images.githubusercontent.com/109055528/178185425-0753d862-8c39-4e95-9183-f23bb31b3d68.png)

**Comment by Soreepeong** [comment]
What's the python version that comes with your installation of Debian? The code has been written with the assumption the python would be running on the latest version.

**Comment by LegendOfMatt** [comment]
The version of python that the installation is 3.9.2-3.

**Comment by LegendOfMatt** [comment]
I have gotten it to run by doing python3 instead of python but now I get this Oodle test fail. 
![image](https://user-images.githubusercontent.com/109055528/178202080-69bd0f63-b4db-4e38-a11f-37e895b9eefe.png)

**Comment by MagickedMike** [comment]
Did you find out how to fix it?
