### ISSUE TITLE
OodleHelper.Runtime Error

### ISSUE THREAD

**Issue by quoehhh** [Soreepeong/XivMitmLatencyMitigator#59]
hi soreepeong. can you check on this error? i tried to run your script on my cloud vps.
- ive already installed all gcc,g++
- have the latest ffxiv.exe on root directory

![mitigatepy_error](https://user-images.githubusercontent.com/74441901/191156596-ee99d3c0-d2c0-474c-9f78-04f91b2a3aa9.JPG)

**Comment by Soreepeong** [comment]
Try replacing "c++20" to "c++2a" in the script. Both works on my arch box, and not sure why would it reject c++20 and suggest c++2a instead, but yeah.

**Comment by ramvalin** [comment]
hello. thank you for the quick response

ive already tried that before but got this results instead.
![image](https://user-images.githubusercontent.com/74441901/191157401-5a9721eb-3b17-43cc-8d8b-2a1a59d72975.png)

**Comment by quoehhh** [comment]
hello there again.
its working now by trying to create new 22.04 imageof ubuntu and script flawlessly run there.

but my current cloud-vps im afraid i cant upgrade it to 22.04 as it might break some of my currently running services there.
maybe you have some workarounds regarding this compiler errors?

**Comment by quoehhh** [comment]
UPDATE: i finally made it work on my version 20.04 of ubuntu
I removed g++ and installed g++-10,g++-10-multilib instead.

I also edited the script to use g++-10 instead of g++(which is version9 and doest support std:span)

**Comment by quoehhh** [comment]
hello. and im back again with another problem xD

currently, im using my vps as forward proxy server. im using proxifier to send my game traffics to the vps(proxy server).
this is my best option with regards to gaming as i dont want to use VPN and it helps me on alot of other mmorpg games

now upon checking the script, and how it works, (correct me if im wrong) it PREROUTES incoming traffic to the scripts random socket and then routes it back to the internet.

with my vps setup, the server itself is the incoming traffic since he is acting as a proxy to forward requests to the game server.
and PREROUTING table will surely not work (also tried). I tried replacing PREROUTING to OUTPUT on the script, but the script just went on loop because im just REDIRECTING traffic endlessly on my vps.

tldr: how can i just make the script work without touching the iptables? do you have source python script that works on linux just like how it works on windows?
