### ISSUE TITLE
Question: VM is far from gaming rig

### ISSUE THREAD

**Issue by quoehhh** [Soreepeong/XivMitmLatencyMitigator#62]
just a quick question.

If i run the script thru VM that is running on the cloud (meaning that would increase my latency for like 30-40ms)
Is it possible to adjust the extra delay below 50ms to cope up with the increased 30-40ms increased?
Or it will put my VM on a redflag from the gameserver?

**Comment by Soreepeong** [comment]
You can always do that with `-e [float_delay_in_seconds_unit], or, you can use `-m` option to make it measure latency and adjust automatically.

**Comment by quoehhh** [comment]
normal setup
client --- 1ms --- VM ---------120ms --------- server

now my setup is like this
client --- 40ms --- VM --------- 80ms --------- server


now what i did is changed the default 75ms to 25ms.
i was just hoping this is safe and would'nt put a red flag against me.

**Comment by Soreepeong** [comment]
The server doesn't really care, and will issue rollbacks/cancellations if something's wrong. Just be reasonable, as in, if you aren't getting those rollbacks, you should be fine from the perspective of keeping your SE account safe. On the other hand, if you're parsing, you probably are better off with not changing that. I'm on 140ms and 0.075 works just fine for me anyway.

**Comment by quoehhh** [comment]
since i feel like im safe to say it here but im using ahk, and im using sleep times of 625 between actions to insert 3 ogcd in between of gcd. A 30-40ms increase would ruin my ahk script and possibly skips the 2nd gcd.

1st GCD (0s)
 - 0.625 ogcd1
 - 1.250 ogcd2
 - 1.875 ogcd3
 2nd GCD (2.5s)

**Comment by quoehhh** [comment]
i tried turning on the --measure-ping syntax to true and i got this results

![image](https://user-images.githubusercontent.com/74441901/191895228-2391e2af-9745-4b79-b3b8-d889cb2affef.png)

this is way far below than the default 75ms! im still confused on reading the rtt computation but would you mind shedding some light here xD why --measure-ping is disabled by default.
