### ISSUE TITLE
Cleanup named "<stdin>.cleanup.sh" and oodle_helper placed in / instead of working directory

### ISSUE THREAD

**Issue by steponmepls** [Soreepeong/XivMitmLatencyMitigator#66]
When I manually execute `run.sh` the cleanup happens without problems on `Ctrl+C`.
When started as a systemd service, the following happens:
- Cleanup script named `<stdin>.cleanup.sh`
- Cleanup not happening on service stop request leaving rules in iptables
- oodle_helper generated in `/` instead of `WorkingDirectory`

I can only assume the lack of cleanup is due to a name mismatch but I don't quite get why `oodle_helper` is placed in `/`. This happens if I manually execute run.sh and if I manually pipe the curl output in python. It should be mentioned that I'm running this in a live CD, similarly to how Arch is run the documentation example. I did install and use this script on a normal Debian installation in the past so I know that it works for sure on Debian.

- OS: Finnix (Debian) 5.16.0-4-amd64
- Python 3.9.19

```
root@0:~# ls
 definitions.json   ffxiv.exe   run.sh  '<stdin>.cleanup.sh'
```
```ini
[Unit]
Description=XivAlexander script

[Service]
Type=simple
User=root
WorkingDirectory=/root
ExecStart=/bin/bash run.sh
Restart=on-failure
RestartSec=5

[Install]
WantedBy=multi-user.target
```
```bash
#!/bin/bash

curl https://raw.githubusercontent.com/Soreepeong/XivMitmLatencyMitigator/main/mitigate.py | python3
```

**Comment by Soreepeong** [comment]
https://github.com/Soreepeong/XivMitmLatencyMitigator/blob/a32f36233077da9bcff51e9f6101c915fb954664/mitigate.py#L817-L832

In fact, if mitigate.py has been run via pipe, then `__file__` would be empty, and this `oodle_helper_path` would end up becoming `/oodle_helper`. This path probably can just be `os.path.join(os.getcwd(), "oodle_helper")` instead.

**Comment by steponmepls** [comment]
I replaced os.path.join() both for cleanup.sh and oodle_helper and they are correctly placed in the working directory but the PREROUTING tables are still there after the service stops meaning the cleanup script isn't being run

```bash
root@0:~# iptables -t nat -F PREROUTING
root@0:~# iptables -t nat -L PREROUTING
Chain PREROUTING (policy ACCEPT)
target     prot opt source               destination
root@0:~# service xivalexander start
root@0:~# ls -A xivalexander/
.cleanup.sh  definitions.json  ffxiv.exe  oodle_helper  run.sh
root@0:~# service xivalexander stop
root@0:~# iptables -t nat -L PREROUTING
Chain PREROUTING (policy ACCEPT)
target     prot opt source               destination
REDIRECT   tcp  --  anywhere             27.221.0.0/16        multiport dports tcpmux:65535 redir ports 45244
REDIRECT   tcp  --  anywhere             202.67.52.0/24       multiport dports 1025:65535 redir ports 45244
REDIRECT   tcp  --  anywhere             162.14.0.0/16        multiport dports tcpmux:65535 redir ports 45244
REDIRECT   tcp  --  anywhere             80-239-145-0.teliacarrier-cust.com/24  multiport dports 1025:65535 redir ports 45244
REDIRECT   tcp  --  anywhere             153.254.80.0/24      multiport dports 1025:65535 redir ports 45244
REDIRECT   tcp  --  anywhere             204.2.229.0/24       multiport dports 1025:65535 redir ports 45244
REDIRECT   tcp  --  anywhere             124.150.157.0/24     multiport dports 1025:65535 redir ports 45244
REDIRECT   tcp  --  anywhere             109.244.0.0/16       multiport dports tcpmux:65535 redir ports 45244
REDIRECT   tcp  --  anywhere             183.111.189.0/24     multiport dports 1025:65535 redir ports 45244
REDIRECT   tcp  --  anywhere             119.97.0.0/16        multiport dports tcpmux:65535 redir ports 45244
```

**Comment by steponmepls** [comment]
As a workaround I added `ExecStop=/bin/bash .cleanup.sh` to my service but the file keeps staying in the working directory even when `mitigate.py` isn't running

https://github.com/Soreepeong/XivMitmLatencyMitigator/blob/a32f36233077da9bcff51e9f6101c915fb954664/mitigate.py#L1657

**Comment by steponmepls** [comment]
This issue has been resolved thanks to https://github.com/Soreepeong/XivMitmLatencyMitigator/issues/66#issuecomment-1287760129 since `.cleanup.sh` is being now named properly and `oodle_helper` is being placed in the working directory so I'll just close this issue and maybe open a new one for the systemd problem.
