### ISSUE TITLE
Not working (06/03/2021)

### ISSUE THREAD

**Issue by igordaniel** [Soreepeong/XivMitmLatencyMitigator#7]
until yesterday it was working perfectly. But today I was unable to connect. I redid all the steps, but it still doesn't work.
![humm](https://user-images.githubusercontent.com/40151828/110225424-41596700-7ec4-11eb-94bf-d595aff1e7e7.PNG)

**Comment by Soreepeong** [comment]
Unable to connect to github? You might have to set up Hyper-V networking again. It's also possible that your router for some reason isn't allocating additional IPs, if your router is provided from your internet service provider, in which case you might need an another router.

**Comment by igordaniel** [comment]
Ohh. working again! TY!
![Capturar](https://user-images.githubusercontent.com/40151828/110341412-1298d900-8009-11eb-9769-9abd501e48db.PNG)
