### ISSUE TITLE
New code is working

### ISSUE THREAD

**Issue by Arkzera** [Soreepeong/XivMitmLatencyMitigator#75]
I saw the commit is listed as untested and didnt find any place to feedback, so Im sorry if this is not the proper place, but the new code is working just fine, thaank you very much @Soreepeong for all your hard work with the project.
![image](https://user-images.githubusercontent.com/107169291/223585988-6b4eb6d2-39e4-46ea-af1c-8d734f5f4c60.png)

**Comment by Soreepeong** [comment]
Thanks for confirming!
