### ISSUE TITLE
6.35 issue

### ISSUE THREAD

**Issue by RayLynx** [Soreepeong/XivMitmLatencyMitigator#76]
![image (1)](https://user-images.githubusercontent.com/98320763/223757529-3d806cba-a678-4955-b55d-3ac84876333c.png)

I'm having this error when trying to use it on playstation 5, some friends are also not able to use it, any idea what it could be or how to solve it?

**Comment by GSTDiandre** [comment]
Update your ffxiv executable.

**Comment by tsugako** [comment]
same problem here
![image](https://user-images.githubusercontent.com/116118261/223857335-ae8ab7fe-ad16-43d9-8413-666216c5e3fe.png)

**Comment by BarcodeIII** [comment]
Mine is also broke rip rip :( 
![46E076DF-9EDA-4971-A875-2333F9F34709](https://user-images.githubusercontent.com/127361645/223885802-b0aa654a-f59b-4d2b-ab55-e7ca986721fd.jpeg)

**Comment by xivseiken** [comment]
![brokenpipe](https://user-images.githubusercontent.com/127422294/224070883-dd14d701-00c4-4a62-bff6-1df5b2c03b01.jpg)

I'm having the same issue as above, even made a clean install but still get this. Does anyone know how to fix it?

**Comment by bankjaneo** [comment]
What version of ffxiv.exe do you use?

**Comment by xivseiken** [comment]
I got my executable through a MF link instead of using the HFS method. Don't know how to check it. It was working before the latest update. 

But if this could be the issue, I will download the game on my laptop and attempt with a fully updated one. Thank you.
