### ISSUE TITLE
Issue with recent patch

### ISSUE THREAD

**Issue by sleong67** [Soreepeong/XivMitmLatencyMitigator#78]
Hi. I couldn't find a solution anywhere in the previous issues but after the recent patch I'm getting the following error:

![image](https://user-images.githubusercontent.com/81522184/224574442-546bb053-bbbc-4fb7-83b8-15267cacdb25.png)

Already update the ffxiv.exe client to the last version.

Can anyone give some advice on what's happening? Thanks in advance.

**Comment by Soreepeong** [comment]
It requires python3.10 at the moment. But since it's a trivial change, will make it more compatible soon.

**Comment by ayyaruq** [comment]
It might be worth adding `mypy` to a CI job or something, then test against specific Python versions with nox/tox/gha/whatever. It's probably best to target 3.8 until distros catch up with the 3.10 typing changes (ie people to upgrade Ubuntu LTS 20->22, or TinyCore for router use generally being stuck on 3.9 I think it is).

**Comment by bankjaneo** [comment]
May I propose another solution for Linux newbie friendly? Try the unofficial docker version https://github.com/bankjaneo/XivMitmDocker. It's packed with everything including automatic iptables rules.

**Comment by sleong67** [comment]
> It requires python3.10 at the moment. But since it's a trivial change, will make it more compatible soon.

Thank you. With yesterday's update, it is working fine now.
