### ISSUE TITLE
Error: need ffxiv_dx11.exe in the same directory

### ISSUE THREAD

**Issue by DiegoSalazar231** [Soreepeong/XivMitmLatencyMitigator#79]
Hi. I´m having troubles a few  days ago since I change my lan cable to my laptop. Now it gives me this error, I´ve already installed everything again and updated to the last version ffxiv.exe. If someone might tell me what I am doing wrong, I´ll highly appreciate <3

![ffxivS](https://user-images.githubusercontent.com/98240637/225204242-28c921e7-4d5a-4a36-a0cb-6e2382d97119.png)

**Comment by bankjaneo** [comment]
You need `ffxiv_dx11.exe` now. Not the `ffxiv.exe`

**Comment by DiegoSalazar231** [comment]
It works <3 I didn´t know about that change. Thank you so much
