### ISSUE TITLE
Route preventing access to lodestone

### ISSUE THREAD

**Issue by adfly-1** [Soreepeong/XivMitmLatencyMitigator#8]
Is the route passing 124.150.157.0/24 through the vm needed? It only seems to be used for the lodestone and not any of the servers and I can't access the lodestone when using it.

**Comment by Soreepeong** [comment]
From where I'm accessing game servers from, apparently some Korean IP addresses are classified as Chinese IP addresses by sqex servers, and hence is disallowed from accessing xiv web services, so I just added lodestone addresses too, but regardless it should have worked even with routing the whole lodestone. I'll see what can I do to fix this.

**Comment by adfly-1** [comment]
some logs if they help at all
https://0x0.st/-TYj.log
https://0x0.st/-TY2.log
https://0x0.st/-TY_.log

**Comment by exeedz** [comment]
some ip in 124.150.157.0/24 are used for Japan's game server and Lodestone server

**Comment by ayyaruq** [comment]
> It only seems to be used for the lodestone and not any of the servers

All 3 of the JP DCs use this subnet for instance servers.

**Comment by Soreepeong** [comment]
I believe this issue should be resolved when I fix the proxy code. I'll try fixing that later today.

**Comment by ayyaruq** [comment]
What's the issue there - not waiting for the FIN packet or something?

**Comment by Soreepeong** [comment]
Yeah, both sides of the connection are terminated immediately if either send or recv of either socket results in error. Shouldn't be too difficult to fix.

**Comment by Soreepeong** [comment]
It should be fixed now.
