### ISSUE TITLE
5.5 New Op Codes

### ISSUE THREAD

**Issue by princeabooboo** [Soreepeong/XivMitmLatencyMitigator#9]
Not sure if this is already being researched, but someone I know found the 5.5 opcodes to update the plugin, I do not know how useful they will be for this, but I will post them here anyway.

"ActorCast": "0x03c0",
        "ActorControl": "0x03b5",
        "ActorControlSelf": "0x03c0",
        "AddStatusEffect": "0x01d7",
        "AlwaysOnTop": false,
        "GameServerIpRange": "124.150.157.0/24,195.82.50.0/24,204.2.229.0/24,127.0.0.0/8,10.0.0.0/8,172.16.0.0/12,192.168.0.0/16,",
        "GameServerPortRange": "10000,10001-65535",
        "LogAllIpcMessage": false,
        "MedianRttCalculationCount": 1,
        "RequestUseAction": "0x03b0",
        "RequestUseAction2": "0x01a0",
        "ShowControlWindow": false,
        "ShowLoggingWindow": true,
        "SkillResultResponse01": "0x0204",
        "SkillResultResponse08": "0x01c7",
        "SkillResultResponse16": "0x032a",
        "SkillResultResponse24": "0x035c",
        "SkillResultResponse32": "0x0d20",
        "UseAllIpcMessageLogger": false,
        "UseAutoAdjustingExtraDelay": false,
        "UseEffectApplicationDelayLogger": false,
        "UseHighLatencyMitigation": true,
        "UseHighLatencyMitigationLogging": true,
        "UseOpcodeFinder": true

**Comment by ayyaruq** [comment]
I was running the following but I think at least one opcode is wrong, I could see it processing but GCD clipping was pretty bad, some seem correct tho.

```python
self.SUBTYPE_RESPONSE_ACTOR_CAST = 0x00b6
self.SUBTYPE_RESPONSE_ACTOR_CONTROL = 0x03b5
self.SUBTYPE_RESPONSE_ACTOR_CONTROL_SELF = 0x03c0
self.SUBTYPE_RESPONSE_ACTION_RESULT = [0x0204, 0x01c7, 0x032a, 0x035c, 0x02c5]

self.SUBTYPE_REQUEST_ACTION = 0x0387
```

**Comment by Soreepeong** [comment]
I've reflected the changes, but I only applied the new opcodes. Please let me know if something's not working right.

**Comment by ayyaruq** [comment]
Looks like you've got duplicate opcodes for actor cast and actor control self. The commit has both at 0x3C0.

**Comment by Soreepeong** [comment]
Yep, that was a copy & paste error. It should have been 0x00b6.

**Comment by cinnamonbird** [comment]
Sorry if this is a dumb question, but does the updated opcodes mean it should work for the 5.5 patch now?

Thanks for the good and timely work!

**Comment by Soreepeong** [comment]
Yes, and if it doesn't work, try downloading the latest release again.

**Comment by princeabooboo** [comment]
Everything looks good to me, thank you!
