### ISSUE TITLE
Launcher can't connect to servers

### ISSUE THREAD

**Issue by lmlumael** [Soreepeong/XivMitmLatencyMitigator#92]
Hi, so I've managed to follow all the steps of the guide, but my launcher can't connect to the internet after changing the Default Gateway to the one of my Virtual Machine. Everything else can access the internet, just not the FFXIV launcher on PS5.

![Imagem do WhatsApp de 2023-12-06 à(s) 21 20 42_f289f2bc](https://github.com/Soreepeong/XivMitmLatencyMitigator/assets/130233507/f895d91f-b76d-415a-85a8-d198a9ef7253)
![Imagem do WhatsApp de 2023-12-06 à(s) 21 20 46_4e34bfd3](https://github.com/Soreepeong/XivMitmLatencyMitigator/assets/130233507/81f6c5e7-7565-47a5-952c-76170a90a9d2)
(about the "sudo phython3" it's because I was desperatly looking threads here trying to find a solution and one person suggested using so. It didn't help, and using "python" like the guide suggest has the same results)

As you can see I've managed to run the "mitigate.py" but no entries are made when launching FFXIV on PS5, probably because it can't even access the internet after changing the Default Gateway. 

I'm honestly at a loss here... I'm very newbie in virtual machines and it was very hard to make everything work but now at the last step I just can't figure out what went wrong. Is it because I'm using a full Wireless connection? (both PC and PS5) Does one of them need to be wired in order for it to work?

Thanks in advance!

**Comment by bankjaneo** [comment]
Could you show the result of command `ip addr show` from your VM?

At step 6 on the guide https://github.com/Soreepeong/XivMitmLatencyMitigator, what exact command did you use?

**Comment by lmlumael** [comment]
I don't remember what I used on Step 6 and I think it's not relevant anymore since I switched to the Docker, right? Or should I still follow Step 6?

**Comment by bankjaneo** [comment]
No worries about delay responses, because I might end of in same situation as yours too.

If you are using my docker version, you can skip almost everything except set net.ipv4.ip_forward=1 which the normal version doesn't need to. You can check the setting by this command and show me the result.

`cat /etc/sysctl.conf | grep net.ipv4.ip_forward`

When everything is set, `docker logs -f xiv-mitm-latency-mitigator` should always show most events that PS5 interact with the game through xiv-mitm-latency-mitigator such as connection status or some codes of skill that you pressed.

Also the gateway for PS5 should come from `eth0` interface, in your case is `192.168.0.7`

**Comment by lmlumael** [comment]
![image](https://github.com/Soreepeong/XivMitmLatencyMitigator/assets/130233507/ffe9b503-6e09-4c89-9e15-a888e1698611)
So it should be working properly, but I still can't connect to the FFXIV launcher, PS Store, browser, and apps like youtube etc works fine.

My Default Gateway is 192.168.0.7 as you can see in the picture below:
![Imagem do WhatsApp de 2023-12-07 à(s) 12 51 01_9383a3bd](https://github.com/Soreepeong/XivMitmLatencyMitigator/assets/130233507/53632878-3310-4e7e-abc6-bd046285de44)

And no entries on VM
![image](https://github.com/Soreepeong/XivMitmLatencyMitigator/assets/130233507/b993db7c-5069-4543-a9f0-fb9a6f7b956b)

**Comment by lmlumael** [comment]
I've noticed that the eth0 ip address showing there is different from the ip address shown when I use `ip addr show`, is that a problem?

**Comment by bankjaneo** [comment]
Everything seems to be in good order. That 192.168.0.0/24 is good. It means allow all device in your LAN to route network through your VM to any destination (0.0.0.0/0).

The fact that every other apps are working fine except FFXIV is your PS5 having problem routing FFXIV traffic through your VM.

Could you show me more result from this command while docker is still running?

`sudo iptables -t nat -L PREROUTING -n -v`

And you may want to try this command and start FFXIV again.

`sudo iptables -t nat -A POSTROUTING -o eth0 -j MASQUERADE`

**Comment by bankjaneo** [comment]
I just remembered that some guy was having this very same problem when using Wi-Fi, can you try using wired connection to your PC instead?

Don't forget to check if VM IP is changed, so you can put the correct one in your PS5 network gateway setting.

**Comment by lmlumael** [comment]
I changed the primary and secundary DNS and I was able to open FFXIV properly, but no entries were made on the VM and I was still clipping heavily when double weaving. When turning off the VM the PS5 loses connection to the internet, so it was indeed using the VM.

I also tried VirtualBox, but I couldn't make my PS5 connect using the IP of the VM as the Default Gateway. Here are the results of `ip addr show` on the newly VirtualBox VM:
![image](https://github.com/Soreepeong/XivMitmLatencyMitigator/assets/130233507/03dea933-a90f-4603-84b7-0467767ad2e5)
as you can see it shows "enp0s3" instead of "eth0", don't know if that is an issue

and here are the network settings of the VM:
![image](https://github.com/Soreepeong/XivMitmLatencyMitigator/assets/130233507/844f55ae-f675-4254-a45c-0cce6fb14d75)

Everytime I boot the Hyper-V VM it messes my network configs and I have to delete the device it created on the settings of my computer in order for VirtualBox to recognize my Wireless card (I saw you commenting on that on another post here).

I'm thinking of trying wired connection next, can I use wired from my PC and my PS5 still wireless or do both need to have wired connection?

**Comment by bankjaneo** [comment]
Congratulation! So this means wireless connection is not working?

For PS Network, if everything is setup properly, there shouldn't be a problem. You can stick to 8.8.8.8 and 8.8.4.4.

**Comment by bankjaneo** [comment]
I think the best way to check this issue is trying to play without VM by revert the gateway back to `192.168.0.1`.

Normally, playing game through VM, there should be an increase in latency about 1-2 ms which is usually not noticeable. If this issue only occur while playing through VM, there should be something wrong with network performance of your Windows machine that hosted VM.

**Comment by bankjaneo** [comment]
Always happy to help fellow warrior of lights.

For the question about update in the future, if that update does not require a newer version of `ffxiv_dx11.exe` (which usually don't), docker user version like you, easiest way is to just restart VM after an updated Opcode is released. After restart, XivMitm will restart itself and fetch for latest Opcode automatically. You can check at https://github.com/Soreepeong/XivAlexander/tree/main/StaticData/OpcodeDefinition and see the updated date of `game.JP.2023.11.09.0000.0000.json` file.

However, if that update require newer version of `ffxiv_dx11.exe`, I'll need to update the container image first. You may need to check my repo at https://github.com/bankjaneo/XivMitmDocker for progress and follow the update container image guide below. After that just go through basic usage again.

PS. I'm leaving FFXIV soon but many of my friends are still using this docker version so I'll continue to update it, just may took a little bit longer for each update. Luckily that the delay only affect updates that need newer version of `ffxiv_dx11.exe`.

**Comment by lmlumael** [comment]
I see, thanks for the info!

I understand, I myself am not playing as much as I used to as well, I mostly keep my sub because of my house and because every few days I feel like doing an Alliance roullete or something like that. Hope to see you back in the future, and no worries about the updates, do as you can, we can still use the normal version if it comes to that.

But anyway, thanks so much for your help!
