### ISSUE TITLE
Eth0 confusion

### ISSUE THREAD

**Issue by K-rek** [Soreepeong/XivMitmLatencyMitigator#96]
Hey there, less an issue and more of a question. What all do I need to put in place of the eth0?

**Comment by bankjaneo** [comment]
Assuming that you have only one network interface for Internet access. You can use this command to find that interface name.

`ip route get 8.8.8.8 | awk -- '{printf $5}'`

**Comment by K-rek** [comment]
> Assuming that you have only one network interface for Internet access. You can use this command to find that interface name.
> 
> `ip route get 8.8.8.8 | awk -- '{printf $5}'`

So I'm trying to follow the guide and it shows the result of `ip addr show` and then says to put in place of `device name` the result of the eth0 in the code in step 6, what all from `ip addr show` is the eht0 I need to use?

**Comment by bankjaneo** [comment]
Yes, in your case replace `device name` with `eth0`.

**Comment by K-rek** [comment]
So now I'm confused with both copying the game into the vm and the mitigation code. Vm isn't recognizing the curl command

**Comment by bankjaneo** [comment]
What Linux distro are you using now? You may need to install curl manually if it didn't come with your Linux distro.

**Comment by K-rek** [comment]
Actually managed to get through it all, but now I'm struggling with routing the ps5 into the vm and the linked guide just goes to an isp homepage
